project:
  type: website
  execute-dir: project
  render:
# - presentation_paper/demo_paper.qmd
  - presentation_paper/rendertest.qmd

# project:
#   type: manuscript
#   execute-dir: project
# manuscript:
#   article: presentation_paper/demo_paper.qmd
#
execute:
  freeze: false
#
format:
  # html:
  #   toc: true
  #   comments:
  #     hypothesis: true
  docx:
    toc: true
    prefer-html: true
#   jats: default
#   elsevier-pdf: default
